//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen
    {
        public string CMND_CCCD { get; set; }
        public string fullName { get; set; }
        public bool gender { get; set; }
        public System.DateTime birth { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public System.DateTime regisDay { get; set; }
        public int vaccination { get; set; }
    }
}
